ALTER TABLE public.emergency_requests
ADD COLUMN IF NOT EXISTS resolved_place_name TEXT;

ALTER TABLE public.missions
ADD COLUMN IF NOT EXISTS volunteer_start_lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS volunteer_start_lng DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS latest_volunteer_lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS latest_volunteer_lng DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS route_distance_km DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS route_duration_minutes DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS route_mode TEXT DEFAULT 'car',
ADD COLUMN IF NOT EXISTS route_summary TEXT,
ADD COLUMN IF NOT EXISTS route_polyline JSONB,
ADD COLUMN IF NOT EXISTS alternate_route_polyline JSONB,
ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
